const models =
	[
   {
      "fileName":"escape.obj",
      "name":"g0",
      "xPosit":"0",
      "yPosit":"1.5",
      "zPosit":"-11.4",
      "yRot":"0.55",
      "textureFileName":"t0.png",
      "rotPerSec":"13.708",
      "orbitArm":"0.0"
   },
   {
      "fileName":"escapePinion.obj",
      "name":"g1",
      "xPosit":"0",
      "yPosit":"1.5",
      "zPosit":"-11.4",
      "yRot":"0.55",
      "textureFileName":"t1.png",
      "rotPerSec":"13.708",
      "orbitArm":"0.0"
   },
   {
      "fileName":"ringGear.obj",
      "name":"g2",
      "xPosit":"0",
      "yPosit":"2",
      "zPosit":"0",
      "yRot":"0",
      "textureFileName":"t2.png",
      "rotPerSec":"-0.48959",
      "orbitArm":"0.0"
   },
   {
      "fileName":"drive.obj",
      "name":"g3",
      "xPosit":"3.85",
      "yPosit":"1",
      "zPosit":"3.85",
      "yRot":"0.0",
      "textureFileName":"t3.png",
      "rotPerSec":"0.0083333333333",
      "orbitArm":"0.0"
   },
   {
      "fileName":"drivePinionMinutes.obj",
      "name":"g4",
      "xPosit":"0",
      "yPosit":"1",
      "zPosit":"0",
      "yRot":"0.4",
      "textureFileName":"t4.png",
      "rotPerSec":"-0.1",
      "orbitArm":"0.0"
   },
   {
      "fileName":"arm.obj",
      "name":"g5",
      "xPosit":"0",
      "yPosit":"1.5",
      "zPosit":"0",
      "yRot":"0.0",
      "textureFileName":"t5.png",
      "rotPerSec":"-0.1",
      "orbitArm":"0.0"
   },
   {
      "fileName":"planet.obj",
      "name":"g6",
      "xPosit":"-4.65",
      "yPosit":"2",
      "zPosit":"0",
      "yRot":"0",
      "textureFileName":"t6.png",
      "rotPerSec":"-0.92499999999999",
      "orbitArm":"-4.65"
   },
   {
      "fileName":"planetPinion.obj",
      "name":"g7",
      "xPosit":"-4.65",
      "yPosit":"2",
      "zPosit":"0",
      "yRot":"0.393",
      "textureFileName":"t7.png",
      "rotPerSec":"-0.92499999999999",
      "orbitArm":"-4.65"
   },
   {
      "fileName":"sunFreeHour.obj",
      "name":"g8",
      "xPosit":"0",
      "yPosit":"2.5",
      "zPosit":"0",
      "yRot":"0",
      "textureFileName":"t8.png",
      "rotPerSec":"-0.008333333333333",
      "orbitArm":"0.0"
   },
   {
      "fileName":"sunFixed.obj",
      "name":"g9",
      "xPosit":"0",
      "yPosit":"3.0",
      "zPosit":"0",
      "yRot":"1.57",
      "textureFileName":"t9.png",
      "rotPerSec":"0.0",
      "orbitArm":"0.0"
   }
];