const models =
	[
   {
      "fileName":"escape.",
      "name":"g0",
      "xPosit":"0",
      "yPosit":"0",
      "zPosit":"-11.4",
      "yRot":"0.55",
      "textureFileName":"copperPatina.png",
      "rotPerSec":"13.708",
      "orbitArm":"0.0"
   },
   {
      "fileName":"escapePinion.",
      "name":"g1",
      "xPosit":"0",
      "yPosit":"0",
      "zPosit":"-11.4",
      "yRot":"0.55",
      "textureFileName":"copperPatina.png",
      "rotPerSec":"13.708",
      "orbitArm":"0.0"
   },
   {
      "fileName":"ringGear.",
      "name":"g2",
      "xPosit":"0",
      "yPosit":"0.5",
      "zPosit":"0",
      "yRot":"0",
      "textureFileName":"copperPatina.png",
      "rotPerSec":"-0.48959",
      "orbitArm":"0.0"
   },
   {
      "fileName":"drive.",
      "name":"g3",
      "xPosit":"3.85",
      "yPosit":"-0.5",
      "zPosit":"3.85",
      "yRot":"0.0",
      "textureFileName":"copperPatina.png",
      "rotPerSec":"0.0083333333333",
      "orbitArm":"0.0"
   },
   {
      "fileName":"drivePinionMinutes.",
      "name":"g4",
      "xPosit":"0",
      "yPosit":"-0.5",
      "zPosit":"0",
      "yRot":"0.4",
      "textureFileName":"copperPatina.png",
      "rotPerSec":"-0.1",
      "orbitArm":"0.0"
   },
   {
      "fileName":"arm.",
      "name":"g5",
      "xPosit":"0",
      "yPosit":"0",
      "zPosit":"0",
      "yRot":"0.0",
      "textureFileName":"copperPatina.png",
      "rotPerSec":"-0.1",
      "orbitArm":"0.0"
   },
   {
      "fileName":"planet.",
      "name":"g6",
      "xPosit":"-4.65",
      "yPosit":"0.5",
      "zPosit":"0",
      "yRot":"0",
      "textureFileName":"copperPatina.png",
      "rotPerSec":"-0.92499999999999",
      "orbitArm":"-4.65"
   },
   {
      "fileName":"planetPinion.",
      "name":"g7",
      "xPosit":"-4.65",
      "yPosit":"0.5",
      "zPosit":"0",
      "yRot":"0.393",
      "textureFileName":"copperPatina.png",
      "rotPerSec":"-0.92499999999999",
      "orbitArm":"-4.65"
   },
   {
      "fileName":"sunFreeHour.",
      "name":"g8",
      "xPosit":"0",
      "yPosit":"1",
      "zPosit":"0",
      "yRot":"0",
      "textureFileName":"copperPatina.png",
      "rotPerSec":"-0.008333333333333",
      "orbitArm":"0.0"
   },
   {
      "fileName":"sunFixed.",
      "name":"g9",
      "xPosit":"0",
      "yPosit":"1.5",
      "zPosit":"0",
      "yRot":"1.57",
      "textureFileName":"copperPatina.png",
      "rotPerSec":"0.0",
      "orbitArm":"0.0"
   }
];